# Site settings
title: Shuchang Xu
email: xsc14thu@gmail.com
description: >
   Ph.D. candidate at HKUST and visiting student at the MIT Media Lab. I build AI-powered assistive systems that augment human perception and cognition for blind and aging populations.
baseurl: ""
url: "https://shuchangxu.github.io"
github_username: ShuchangXu

# External links
google_scholar: https://scholar.google.com/citations?hl=en&user=aztYItYAAAAJ

# SEO
lang: en-US
author: Shuchang Xu

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - README_de.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - vendor
